# Mariano Villanueva Aguilar
# 9 de septiembre de 2024
# A06 PL

Ejercicio 1.

Una carpintería local fabrica sillas, mesas, libreros y bases de cama. Hay dos empleados en esta carpintería: un empleado experimentado y un aprendiz. El aprendiz tarda aproximadamente 50% más tiempo que el carpintero experimentado en construir cualquier cosa, además de que tiene un desperdicio de alrededor de 20% de material. Los materiales y tiempos necesarios para construir algo se desglozan en la siguiente tabla:

![](C1.png)

Las mesas se venden en 9000 pesos, las sillas en 3000 pesos, los libreros en 10000 pesos, y las bases de cama en 9000 pesos. Suponiendo una jornada de 40 horas a la semana y que tienen 100 unidades de madera.
l?
 

2. La carpintería recibió una orden por 3 combos de mesa + 6 sillas.
   

¿Se puede cumplir la orden?
Si sí, ¿qué es lo que tienen que fabricar en el resto del tiempo y con el resto del material para maximizar su ganancia?
¿Cuántas horas trabaja cada quién?
¿Cuánto material se usa?
¿Cuál es el nuevo ingreso total?
 

1. Identificar criterio 

Se deben de maximizar las ganancias

$$\geq$$

En el menor tiempo posible
$$ \leq $$

Con el menor material
$$ \leq $$

2.Variables de control

$$ M_E,M_A,S_E,S_A,L_E,L_A,B_E,B_A$$

3. Función de costo

$$ Costo= 9000M_E+9000M_A+3000S_E+3000S_A+10000L_E+10000L_A+9000B_E+9000B_A $$

4. Info adicional

Tiempo experimentado
$$ 3M_E+1S_E+4L_E+3B_E\leq40$$
Tiempo aprendiz
$$4.5M_A+1.5S_A+6L_A+4.5B_A\leq40 $$


Material

$$ 6M_E+7.2M_A+2S_E+2.4S_A+5L_E+6L_A+5B_E+6B_A\leq100 $$

5. Vectorizar en forma

In [3]:
import numpy as np
import scipy.optimize as opt
c=np.array([-9000,-9000,-3000,-3000,-10000,-10000,-9000,-9000])
Aub=np.array([
    [3,0,1,0,4,0,3,0],
    [0,4.5,0,1.5,0,6,0,4.5],
    [6,7.2,2,2.4,5,6,5,6]
])
bub=np.array([
    [40],
    [40],
    [100],
])



¿Qué les conviene construir durante una semana para maximizar su ganancia?

In [9]:
sol=opt.linprog(c,Aub,bub, integrality=1)
sol

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -176000.0
              x: [ 0.000e+00  0.000e+00  1.000e+00 -9.474e-15  9.000e+00
                   2.000e+00  1.000e+00  6.000e+00]
            nit: -1
          lower:  residual: [ 0.000e+00  0.000e+00  1.000e+00 -9.474e-15
                              9.000e+00  2.000e+00  1.000e+00  6.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.000e+00  0.00

¿Cuántas horas trabaja cada quién?

In [15]:
sol.x

array([ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, -9.47390314e-15,
        9.00000000e+00,  2.00000000e+00,  1.00000000e+00,  6.00000000e+00])

In [17]:
Aub@sol.x

array([ 40.,  39., 100.])

Se llevan 40 el experimentado y 39 horas el aprendiz 

¿Cuánto material se usa?

Se llevan 100 unidades de material

¿Cuál es el ingreso total si se vende todo lo fabricado?

In [35]:
sol.fun

-176000.0

Se gana en total 176,000 pesos

2. La carpintería recibió una orden por combos de mesa + 6 sillas 

Paso 1: Encontrar criterio

Se deben de maximizar las ganancias
$$\geq$$
En el menor tiempo posible
$$ \leq $$
Con el menor material
$$ \leq $$

Paso 2: Variables
$$ M_E,M_A,S_E,S_A,L_E,L_A,B_E,B_A$$

Paso 3: Función de costo
$$ Costo= 9000M_E+9000M_A+3000S_E+3000S_A+10000L_E+10000L_A+9000B_E+9000B_A $$

Paso 4: Info adicional

Tiempo experimentado
$$ 3M_E+1S_E+4L_E+3B_E\leq40$$

Tiempo aprendiz
$$4.5M_A+1.5S_A+6L_A+4.5B_A\leq40 $$


Material

$$ 6M_E+7.2M_A+2S_E+2.4S_A+5L_E+6L_A+5B_E+6B_A\leq100 $$

Mesa + 6 sillas
$$ M_E+M_A=1 $$
$$ S_E+S_E=6 $$

Paso 5

In [59]:
c=np.array([-9000,-9000,-3000,-3000,-10000,-10000,-9000,-9000])
Aub=np.array([
    [3,0,1,0,4,0,3,0],
    [0,4.5,0,1.5,0,6,0,4.5],
    [6,7.2,2,2.4,5,6,5,6],
])
bub=np.array([
    [40],
    [40],
    [100],
])
Aeq=np.array([
    [1,1,0,0,0,0,0,0],
    [0,0,1,1,0,0,0,0],
])
beq=([
    [1],
    [6],
])

In [71]:
sol1=opt.linprog(c,Aub,bub,Aeq,beq, integrality=1)
sol1

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -173999.99999999997
              x: [ 1.000e+00  0.000e+00  4.000e+00  2.000e+00  6.000e+00
                   6.000e+00  3.000e+00 -5.329e-14]
            nit: -1
          lower:  residual: [ 1.000e+00  0.000e+00  4.000e+00  2.000e+00
                              6.000e+00  6.000e+00  3.000e+00 -5.329e-14]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: [ 0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00]
    

In [76]:
sol1.x

array([ 1.00000000e+00,  0.00000000e+00,  4.00000000e+00,  2.00000000e+00,
        6.00000000e+00,  6.00000000e+00,  3.00000000e+00, -5.32907052e-14])

In [78]:
Aeq@sol1.x

array([1., 6.])

¿Se puede cumplir la orden?

Si

Si sí, ¿qué es lo que tienen que fabricar en el resto del tiempo con el resto del material para maximizar su ganancia?

In [85]:
sol1.x

array([ 1.00000000e+00,  0.00000000e+00,  4.00000000e+00,  2.00000000e+00,
        6.00000000e+00,  6.00000000e+00,  3.00000000e+00, -5.32907052e-14])

El experimentado hizo 6 libreros y 3 bases de cama

El aprendiz hizo 6 libreros 

¿Cuántas horas trabaja cada quién?

In [89]:
Aub@sol1.x

array([40. , 39. , 99.8])

¿Cuál es el nuevo ingreso total?